name: 自动签到

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 0:00 = 北京时间 8:00
  workflow_dispatch:      # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: FlyingBird Auto Checkin
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 运行签到脚本
      env:
        FB_USERNAME: ${{ secrets.FB_USERNAME }}
        FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python checkin.py